import { cp, mkdir, rm } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const output = resolve(root, 'dist')
if (dirname(output) !== resolve(root)) throw new Error('Build output must stay inside the project.')
await rm(output, { recursive: true, force: true })
await mkdir(output, { recursive: true })
// Copy only browser assets. Config modules are generated by the API at runtime.
for (const entry of ['index.html', 'src', 'public']) {
  await cp(join(root, entry), join(output, entry), {
    recursive: true,
    filter: (source) => !/[/\\](spotify|supabase)[/\\]config\.js$/.test(source),
  })
}
console.log('Built browser assets in dist/. Runtime configuration is served by api/index.js.')
